---
title: "Statistical Analysis"
output: pdf_document
date: "2024-10-21"
author: "Sophia Vo, Katelyn Zhao"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Contribution

# 1. Introduction

# 2. Analysis

## 2.1. Estimate Proportions

### 2.1.1. Methods

The first step of our analysis was to estimate the proportion of students who played a video in the week prior to the survey. We found both a point estimate and an interval estimate for this proportion.

### 2.1.2. Analysis

To find the point estimate, we found the sample proportion by counting the number of students whose playing time a week prior to the survey was greater than zero and the total number of responses to the survey.

Point-Estimate: 37.36%

To find the interval estimate, we used a 95% confidence interval. The 95% confidence interval can be represented by
$$
(\bar{x} + 2 \cdot \frac{s}{\sqrt{n}}, \bar{x} - 2 \cdot \frac{s}{\sqrt{n}})
$$
where $\bar{x}$ is the sample proportion, $n$ is the sample size, and $s$ is the sample standard deviation (which can also be represented as $\frac{\sqrt{\bar{x}(1 - \bar{x})}}{\sqrt{n}}$). Using this, we found that our interval estimate is as follows: 

Interval-Estimate: (27.22%, 47.51%)

### 2.1.3. Conclusion

A point estimator is a single value $\bar{x}$. In this case, it estimates the proportion of students that played video games a week prior to the survey given a sample. An interval estimate is a range of two values, where one can estimate that the population proportion is between those two values with a fixed confidence (probability).

# 3. Advanced Analysis

# 4. Discussion

# 5. Appendix
